<?php

echo '  <option value="0"> </option>
        <option value="1">Administração Comercial/Vendas</option>
        <option value="2">Administração de Empresas</option>
        <option value="3">Advocacia/Jurídica</option>
        <option value="4">Arquivologia</option>
        <option value="5">Auditoria</option>
        <option value="6">Comercial</option>
        <option value="7">Compras</option>
        <option value="8">Construção Civil</option>
        <option value="9">Contabilidade</option>
        <option value="10">Desenho Industrial</option>
        <option value="11">Enfermagem</option>
        <option value="12">Engenharia - Outras</option>
        <option value="13">Engenharia Civil</option>
        <option value="14">Engenharia de Minas</option>
        <option value="15">Engenharia de Produção</option>
        <option value="16">Engenharia Eletrotécnica</option>
        <option value="17">Engenharia Eletrônica</option>
        <option value="18">Engenharia Mecânica</option>
        <option value="19">Engenharia Metalúrgica e de Materiais</option>
        <option value="20">Engenharia Química</option>
        <option value="21">Finanças</option>
        <option value="22">Gestão Empresarial</option>
        <option value="23">Logística</option>
        <option value="24">Manutenção Industrial</option>
        <option value="25">Manutenção Predial</option>
        <option value="26">Medicina/Hospitalar</option>
        <option value="27">Organização e Métodos</option>
        <option value="28">Psicologia</option>
        <option value="29">Qualidade</option>
        <option value="30">Recursos Humanos</option>
        <option value="31">Segurança e Saúde no Trabalho</option>
        <option value="32">Segurança Patrimonial</option>
        <option value="33">Serviços Administrativos</option>
        <option value="34">Serviços Gerais</option>
        <option value="35">Serviços Técnicos - Eletrônicos</option>
        <option value="36">Serviços Técnicos - Elétricos</option>
        <option value="37">Serviços Técnicos - Mecânicos</option>
        <option value="38">Serviços Técnicos - Outros</option>
        <option value="39">Suprimentos</option>
        <option value="40">Telecomunicações</option>
        <option value="41">Transporte Terrestre</option>
        <option value="42">Tributária</option>
        <option value="43">Vendas</option>';
?>